#!/bin/bash

## #ddev-generated
## Description: Export a consistent backup
## Usage: mydumper
## Example: ddev mydumper\nddev mydumper --clear --outputdir=dump

mydumper --host=db --user=root --password=root --database=db --debug "$@"
