#!/usr/bin/env bash

## #ddev-generated
## Description: Read the backup from `ddev mydumper`, connect the to destination database and import the backup
## Usage: myloader
## Example: ddev myloader\nddev myloader --directory=dump

myloader --host=db --user=root --password=root --database=db --debug "$@"
